language: php
php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - phpize
    - ./configure
    - make
    - echo -e "\nru_RU.CP1251 CP1251" | sudo tee -a /var/lib/locales/supported.d/ru; sudo locale-gen

script: echo 'n'|make test
