#ifndef UNIFIEDPHP_H
#define UNIFIEDPHP_H

#define UNIFIEDPHP_NAME     "UnifiedPHP"
#define UNIFIEDPHP_VERSION  "0.0.1"

#define UNIFIEDPHP_NS       UNIFIEDPHP_NAME
#define UNIFIEDPHP_NS_STR   UNIFIEDPHP_NS"\\Str"
#define UNIFIEDPHP_NS_ARR   UNIFIEDPHP_NS"\\Arr"

#endif // UNIFIEDPHP_H
